### ISSUE TITLE
Remove TODOs from source code

### ISSUE THREAD

**Issue by hayesall** [hayesall/srlearn#25]
Currently there are quite a few TODOs that are directly embedded in the source code.

These should be removed and opened as issues on GitHub.

**Comment by Elephant34** [comment]
I might be able to help for some of this:
Do you just want each todo deleted from the source and a new issure created for each?
For example each TODO with an issue:
Title: TODO srlearn/system_manager  Line 116
Comment: TODO: Resistance to concurrency, race conditions, and asynchronous problems.

I don't promise to be fast but I should be able to do this

**Comment by hayesall** [comment]
Hey @Elephant34, this would be fantastic! If you would like to fork, branch, and open a "Work-in-progress" pull request you can set the pace that works for you.

> Do you just want each todo deleted from the source and a new issure created for each?

This is exactly it: as long as we have a good way to maintain which TODOs were associated with each file/class/etc.

Multi-line TODOs should be fine to file as a single issue, for example:

https://github.com/hayesall/srlearn/blob/0a0b0941aa3992e39afb2bfff1fb0072567da38b/srlearn/background.py#L20-L26

**Comment by Elephant34** [comment]
I would suggest that this issue can now be closed as of the merge 👍

**Comment by hayesall** [comment]
Closing now. Usually these are closed automatically when "close" and an issue number appear in a pull request. I might need to start another kanban board on the projects page.

Thanks for catching this!
