### ISSUE TITLE
Improvements to Relational Estimators

### ISSUE THREAD

**Issue by Elephant34** [hayesall/srlearn#30]
Line 12: @property: feature_importances_
Line 165: On error, collect log files.
Line 168: This may be possible to set in the base class.

**Comment by hayesall** [comment]
Bit more context:

- `feature_importances_` is related to Issue #12 
- `fit()` function needs more informative error messages.
- Private `_run_inference()` method could likely be done in the `BaseBoostedRelationalModel`.

**Comment by hayesall** [comment]
Mostly fixed, see #57 for the last step.
