### ISSUE TITLE
Model Serialization for saving and loading

### ISSUE THREAD

**Issue by harshakokel** [hayesall/srlearn#53]
I find the need to save the learned BoostSRL models for analysis. Currently, the FileSystem class is auto-deleted. It would help to make that customizable. Also, the paths in FileSystem are fixed. I believe this should also be customizable for the organization of respective experiments.

**Describe if the Java version of BoostSRL already supports this.**
This is possible in BoostSRL, although a little tedious.

**Is your feature request related to a problem? Please describe.**
I am conducting various experiments and I want to make sure I have the models saved for future analysis. To compare various experiments, I need the custom convention for  folders.

**Describe the solution you'd like**
My current solution is to create a `CustomFileSystem` Class that takes path as input. Allow setting of `self.file_system` in the `BaseBoostedRelationalModel`.

**Comment by hayesall** [comment]
I'd like to avoid keeping `FileSystem` objects around (they potentially take up a lot of disk space and have to be cleaned up manually with [`system_manager.reset()`](https://srlearn.readthedocs.io/en/latest/generated/srlearn.system_manager.reset.html#srlearn.system_manager.reset)).

Follow-up question: *Do you need to keep pos/neg/facts, or just the learned models?*

e.g. Would it solve your problem if you could do:

```python
>>> from srlearn.rdn import BoostedRDNRegressor
>>> clf = BoostedRDNRegressor()
>>> ...
>>> clf.to_file("model.zip")
>>> clf.from_file("model.zip")
>>> clf.predict(new_database)
```

> save the learned BoostSRL models for analysis

Does the `clf.estimators_` attribute work for now?

**Comment by harshakokel** [comment]
This is definitely a better solution 👍.  I think saving the model should be enough for analysis. But for debugging purpose the pos/neg/facts shall be saved. Specifically, when we get an error from BoostSRL.

**Comment by hayesall** [comment]
> But for debugging purpose the pos/neg/facts shall be saved. Specifically, when we get an error from BoostSRL.

I didn't even think about that. Resilience is a weakness right now. A debug mode where crash reports and all `FileSystem` content are saved when the `__del__` method triggers could be super helpful for debugging.

Might split this off into another issue.

> I think saving the model should be enough for analysis.

I'll implement this, I think I know where all the changes need to occur.
