### ISSUE TITLE
Setting advanced parameters in mode file

### ISSUE THREAD

**Issue by harshakokel** [hayesall/srlearn#59]
The current Background file allows most of the parameters and modes. There is one specific parameter that is missing `okIfUnknown: [pred]/[#arg].`  In general, I feel there should be some way to add custom lines in the bk file which don't have a prefix like `mode:` or  `setParam:`.

**Is your feature request related to a problem? Please describe.**
Currently, I need to add only 'okIfIUnknown' for some predicates.

**Describe the solution you'd like**
One possible solution is to add another parameter in the Background class
```
parameters = ['okIfUnknown: siblingof/2']
bk = Background(
                modes=data.modes,
                max_tree_depth=2,
                use_std_logic_variables=True,
                more_parameters=parameters
                )
```

**Comment by harshakokel** [comment]
A quick hack can be found here: https://github.com/harshakokel/srlearn/commit/937ab8da890bd8f7a92567af10876efbab636c22

**Comment by hayesall** [comment]
Related to #23 and #33 

`more_parameters` would basically be a `**kwargs`—but this also makes it harder to test and reason about state when arbitrary data can be passed.

`okIfUnknown` definitely needs to be added, maybe:

```python
bkg = Background(
    modes=data.modes,
    use_std_logic_variables=True,
    ok_if_unknown=["siblingof/2"],
)
```
