### ISSUE TITLE
What is the vector of probabilities that you predict?

### ISSUE THREAD

**Issue by sagarAI** [hayesall/srlearn#71]
I am confused regarding what is the vector of probability that you are predicting using  'predict' ?
So for example in the family relationships toy example. When I call 'clf.predict(test_db)', I get a vector of booleans, but How do I know which boolean is associated to which entity ?

I will be immensely thankful for any help!

**Comment by hayesall** [comment]
You got it!

The [`clf.classes_`](https://srlearn.readthedocs.io/en/latest/auto_examples/plot_smokes_friends_cancer.html#sphx-glr-auto-examples-plot-smokes-friends-cancer-py) attribute can also be a shorthand for getting these (e.g. if you're comparing with `sklearn.metrics`)
